proxy-providers:
  CNIX:
    type: http
    url: "è¿™é‡Œéœ€è¦æ›¿æ¢ä¸ºä½ çš„è®¢é˜…é“¾æ¥ï¼Œè¯·ä¿ç•™åŒå¼•å·å’ŒåŒå¼•å·å‰é¢çš„ç©ºæ ¼"
    path: ./cnix.yaml
    interval: 7200

# HTTP ä»£ç†ç«¯å£
port: 7890

# SOCKS5 ä»£ç†ç«¯å£
socks-port: 7891

# Linux å’Œ macOS çš„ redir ä»£ç†ç«¯å£ (å¦‚éœ€ä½¿ç”¨æ­¤åŠŸèƒ½ï¼Œè¯·å–æ¶ˆæ³¨é‡Š)
# redir-port: 7892

# å…è®¸å±€åŸŸç½‘çš„è¿æ¥ï¼ˆå¯ç”¨æ¥å…±äº«ä»£ç†ï¼‰
allow-lan: false

# è§„åˆ™æ¨¡å¼ï¼šGlobalï¼ˆå…¨å±€ä»£ç†ï¼‰/ Ruleï¼ˆè§„åˆ™ï¼‰ / Script(è…³æœ¬) / Directï¼ˆå…¨å±€ç›´è¿ï¼‰
mode: Rule

# è®¾ç½®æ—¥å¿—è¾“å‡ºçº§åˆ« (é»˜è®¤çº§åˆ«ï¼šsilentï¼Œå³ä¸è¾“å‡ºä»»ä½•å†…å®¹ï¼Œä»¥é¿å…å› æ—¥å¿—å†…å®¹è¿‡å¤§è€Œå¯¼è‡´ç¨‹åºå†…å­˜æº¢å‡ºï¼‰ã€‚
# 5 ä¸ªçº§åˆ«ï¼šsilent / info / warning / error / debugã€‚çº§åˆ«è¶Šé«˜æ—¥å¿—è¾“å‡ºé‡è¶Šå¤§ï¼Œè¶Šå€¾å‘äºè°ƒè¯•ï¼Œè‹¥éœ€è¦è¯·è‡ªè¡Œå¼€å¯ã€‚
log-level: info

ipv6: false

# clash çš„ RESTful API
external-controller: '127.0.0.1:9090'


# æ‚¨å¯ä»¥å°†é™æ€ç½‘é¡µèµ„æºï¼ˆå¦‚ clash-dashboardï¼‰æ”¾ç½®åœ¨ä¸€ä¸ªç›®å½•ä¸­ï¼Œclash å°†ä¼šæœåŠ¡äº `${API}/ui`
# å‚æ•°åº”å¡«å†™é…ç½®ç›®å½•çš„ç›¸å¯¹è·¯å¾„æˆ–ç»å¯¹è·¯å¾„ã€‚
# external-ui: folder

# RESTful API çš„å£ä»¤ (å¯é€‰)
# secret: ""

# DNS è®¾ç½®

dns:
 enable: true
 ipv6: false
 listen: 0.0.0.0:53
 enhanced-mode: redir-host
 default-nameserver:
    - 114.114.114.114
 nameserver:
  - tls://223.5.5.5:853
  - 8.8.8.8
  - 1.1.1.1
  - 119.29.29.29
  - 223.5.5.5
  - 180.76.76.76
  - https://rubyfish.cn/dns-quer
 fallback:
  - https://cloudflare-dns.com/dns-query
  - tls://1.0.0.1:853
  - https://dns.google/dns-query#
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.localdomain'
    - '*.example'
    - '*.invalid'
    - '*.localhost'
    - '*.test'
    - '*.local'
    - '*.home.arpa'
    - router.asus.com
    - localhost.sec.qq.com
    - localhost.ptlogin2.qq.com
    - '+.msftconnecttest.com'
tun:
  enable: true
  stack: system
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  dns-hijack:
    - 114.114.114.114
    - 180.76.76.76
    - 119.29.29.29
    - 223.5.5.5
    - 8.8.8.8
    - 8.8.4.4
    - 1.1.1.1
    - 1.0.0.1

proxy-groups:
  - name: PROXY
    type: select
    proxies:
      - CNIX
      - DIRECT
  - name: CNIX
    type: select
    use:
      - CNIX

rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 36000

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 36000

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 36000

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 36000

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 36000

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 36000

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 36000

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 36000

rules:
  - PROCESS-NAME,clash,DIRECT
  - PROCESS-NAME,clash-darwin,DIRECT
  - PROCESS-NAME,clash-windows,DIRECT
  - PROCESS-NAME,clash-linux,DIRECT
  - PROCESS-NAME,surge,DIRECT
  - PROCESS-NAME,surge%203,DIRECT
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,thunder.exe,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qbittorrent,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,reject,REJECT
  - DOMAIN,www.icloud.com,PROXY
  - DOMAIN-SUFFIX,icloud-content.com,PROXY
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,PROXY
  - RULE-SET,google,PROXY
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - GEOIP,,DIRECT,no-resolve
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,PROXY

;è®¾ç½®è§„åˆ™æ ‡å¿—ä½
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=ğŸƒ åº”ç”¨å‡€åŒ–,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=ğŸ† AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=ğŸ† AdBlock,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=ğŸ›¡ï¸ éšç§é˜²æŠ¤,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=ğŸ“¢ è°·æ­ŒFCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=â“‚ï¸ å¾®è½¯äº‘ç›˜,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/OneDrive.list
ruleset=ğŸ è‹¹æœæœåŠ¡,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=ğŸ“² ç”µæŠ¥æ¶ˆæ¯,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=ğŸ® æ¸¸æˆå¹³å°,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=ğŸ® æ¸¸æˆå¹³å°,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=ğŸ® æ¸¸æˆå¹³å°,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=ğŸ“¹ æ²¹ç®¡è§†é¢‘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/YouTube.list
ruleset=ğŸ¥ å¥ˆé£è§†é¢‘,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Netflix.list
ruleset=ğŸŒ å›½å¤–åª’ä½“,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bahamut.list
ruleset=ğŸ“º å“”å“©å“”å“©,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Bilibili.list
ruleset=ğŸ“º å“”å“©å“”å“©,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/BilibiliHMT.list
;ruleset=ğŸ¶ ç½‘æ˜“éŸ³ä¹,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/NetEaseMusic.list
ruleset=ğŸŒ å›½å†…åª’ä½“,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaMedia.list
ruleset=ğŸŒ å›½å¤–åª’ä½“,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=ğŸš€ èŠ‚ç‚¹é€‰æ‹©,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=ğŸš€ èŠ‚ç‚¹é€‰æ‹©,https://raw.githubusercontent.com/hope140/Clash/main/Proxy.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaIp.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Download.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://raw.githubusercontent.com/hope140/Clash/main/Direct.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,[]GEOIP,CN
ruleset=ğŸŸ æ¼ç½‘ä¹‹é±¼,[]FINAL
;è®¾ç½®è§„åˆ™æ ‡å¿—ä½

;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½
custom_proxy_group=ğŸš€ èŠ‚ç‚¹é€‰æ‹©`select`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸ”¯ æ•…éšœè½¬ç§»`[]ğŸ”® è´Ÿè½½å‡è¡¡`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=â™»ï¸ è‡ªåŠ¨é€‰æ‹©`url-test`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ”¯ æ•…éšœè½¬ç§»`fallback`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ”® è´Ÿè½½å‡è¡¡`load-balance`.*`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=ğŸ“² ç”µæŠ¥æ¶ˆæ¯`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ“¹ æ²¹ç®¡è§†é¢‘`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ¥ å¥ˆé£è§†é¢‘`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸ“º å“”å“©å“”å“©`select`[]ğŸ¯ å…¨çƒç›´è¿`[]ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹`[]ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
custom_proxy_group=ğŸŒ å›½å¤–åª’ä½“`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢`[]DIRECT
custom_proxy_group=ğŸŒ å›½å†…åª’ä½“`select`[]DIRECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ“¢ è°·æ­ŒFCM`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=â“‚ï¸ å¾®è½¯äº‘ç›˜`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ è‹¹æœæœåŠ¡`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ® æ¸¸æˆå¹³å°`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
custom_proxy_group=ğŸ¯ å…¨çƒç›´è¿`select`[]DIRECT`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©
custom_proxy_group=ğŸ›‘ å¹¿å‘Šæ‹¦æˆª`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸƒ åº”ç”¨å‡€åŒ–`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸ† AdBlock`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸ›¡ï¸ éšç§é˜²æŠ¤`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸŸ æ¼ç½‘ä¹‹é±¼`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`[]DIRECT`[]ğŸš€ æ‰‹åŠ¨åˆ‡æ¢
;è®¾ç½®åˆ†ç»„æ ‡å¿—ä½

enable_rule_generator=true
overwrite_original_rules=true

;clash_rule_base=https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GeneralClashConfig.yml

;luck
